### ISSUE TITLE
I can't resume the installation.

### ISSUE THREAD

**Issue by alvazhang79** [DeTeKe/HP800G1DM_Hackintosh#3]
I can't continue to boot just after using USB flash disk. The log files are as follows:

00:000 00:000 OCUI: Failed to load images

00:013 00:013 OC: External interface failure, fallback to builtin - Unsupported

Using # Catalina (10.15) and # latest version is the same error message.

**Comment by DeTeKe** [comment]
Try this https://github.com/DeTeKe/HP800G1DM_Hackintosh/tree/d9a2088f3dce863f102558aac631ef9cfcd3e1fd

**Comment by alvazhang79** [comment]
The problem has been solved.
